/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 72;
=======
<<<<<<< HEAD
const int buildversion = 39;
=======
const int buildversion = 48;
>>>>>>> origin/main
>>>>>>> 4e58057211211385855240d00355b59889968234
const char buildconfig[] = "PAGING";
